export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <footer className="flex justify-between items-center p-4 bg-gray-800 text-white">
          footer
        </footer>
      </body>
    </html>
  )
}
