import "./styles.css"


export const metadata = {
  title: {
    default: 'Create Next App',
    template: '%s | Create Next App',
    // absolute: "https://nextjs.org",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className="flex justify-between items-center p-4 bg-gray-800 text-white">
          header
        </header>
        {children}
        <footer className="flex justify-between items-center p-4 bg-gray-800 text-white">
          footer
        </footer>
      </body>
    </html>
  )
}
